---
- name: Update distribution (CentOS)
  command: yum -y update
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  sudo: yes
  sudo_user: root

- name: Update distribution (Debian)
  command: apt-get -y update
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  sudo: yes
  sudo_user: root

- name: Install git, postgresql-clients (CentOS)
  yum: name={{ item }} state=present
  with_items:
  - wget
  - git
  - postgresql
  - postgresql-devel
  - nginx
  sudo: yes
  sudo_user: root
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  
- name: Install git, postgresql-clients (Debian)
  apt: name={{ item }} state=present
  with_items:
  - wget
  - git
  - postgresql-client
  - libpq-dev
  - nginx
  sudo: yes
  sudo_user: root
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'



